likelihood_config:
  template_folder: null  # will try to find the templates in alea
  likelihood_terms:
    # SR2
    - name: sr2
      default_source_class: alea.template_source.TemplateSource
      likelihood_type: blueice.likelihood.UnbinnedLogLikelihood
      analysis_space:
        - cs1: np.linspace(0, 100, 51)
        - cs2: np.geomspace(100, 100000, 51)
      in_events_per_bin: true
      livetime_parameter: livetime_sr2
      slice_args: {}
      sources:
      - name: er
        class: alea.template_source.CombinedSource
        parameters:
          - er_rate_multiplier
          - er_band_shift
        named_parameters:
          - er_band_shift
        fixed_weight: 0.2
        weight_names: [fixed_weight, er_band_shift]  # not meaningful, just an example
        histnames: [er_template, er_template, er_template]
        template_filenames: [er_template_0.h5, er_template_1.h5, er_template_-1.h5]
        histogram_scale_factor: 100  # absolute rate, /year

      - name: wimp
        histname: wimp_template
        parameters:
          - wimp_rate_multiplier
          - wimp_mass
          - signal_efficiency
        template_filename: wimp50gev_template.h5
        apply_efficiency: True
        efficiency_name: signal_efficiency

    # SR3
    - name: sr3
      default_source_class: alea.template_source.TemplateSource
      likelihood_type: blueice.likelihood.UnbinnedLogLikelihood
      analysis_space:
        - cs1: np.linspace(0, 100, 51)
        - cs2: np.geomspace(100, 100000, 51)
      in_events_per_bin: true
      livetime_parameter: livetime_sr3
      slice_args: {}
      sources:
      - name: er
        histname: er_template
        parameters:
          - er_rate_multiplier
          - er_band_shift
        named_parameters:
          - er_band_shift
        template_filename: er_template_{er_band_shift}.h5

      - name: wimp
        class: alea.template_source.SpectrumTemplateSource
        histname: wimp_template
        parameters:
          - wimp_rate_multiplier
          - wimp_mass
          - signal_efficiency
        template_filename: wimp50gev_template.h5
        spectrum_name: test_cs1_spectrum.json
        apply_efficiency: True
        efficiency_name: signal_efficiency
