statistical_model: alea.models.BlueiceExtendedModel
statistical_model_config: unbinned_wimp_statistical_model.yaml

poi: wimp_rate_multiplier

computation_options:
  discovery_power:
    to_zip: {}
    to_vary:
      {
        poi_expectation: "np.linspace(0, 30, 10)",
        wimp_mass: [50],
      }
    in_common:
      {
        hypotheses: ["free", "null", "true"],
        output_file: "toymc_power_wimp_mass_{wimp_mass:d}_poi_expectation_{poi_expectation:.2f}.h5",
        n_mc: 5000,
        n_batch: 40,
        toydata_mode: "generate",
      }

  threshold:
    to_zip: {}
    to_vary: {wimp_mass: [50]}
    in_common:
      {
        hypotheses: ["free", "null", "true"],
        output_file: "toymc_power_wimp_mass_{wimp_mass:d}_poi_expectation_{poi_expectation:.2f}.h5",
        n_mc: 5000,
        n_batch: 40,
        limit_threshold: "thresholds.h5",
        toydata_mode: "generate",
        parameters_as_wildcards: ["poi_expectation", "n_mc", "n_batch"],
      }

  sensitivity:
    to_zip: {}
    to_vary: {poi_expectation: [0.], wimp_mass: [50]}
    in_common:
      {
        hypotheses: ["free", "null", "true"],
        output_file: "toymc_power_wimp_mass_{wimp_mass:d}_poi_expectation_{poi_expectation:.2f}.h5",
        n_mc: 5000,
        n_batch: 40,
        compute_confidence_interval: True,
        limit_threshold: "thresholds.h5",
        toydata_mode: "generate",
      }

midway_configurations:
  template_path: null
  hours: 1.5
  mem_per_cpu: 8000
  container: "xenonnt-development.simg"
  partition: "xenon1t"
OSG_configurations:
  template_path: null
  request_memory: "8000Mb"
  singularity_container: null

outputfolder: null
